#!/usr/bin/env bash
# Exports the compiled ABI into the frontend so wagmi/viem get typed contract bindings.
set -euo pipefail
cd "$(dirname "$0")/.."
forge build --silent
mkdir -p ../frontend/src/contracts
node -e '
const fs = require("fs");
const artifact = JSON.parse(fs.readFileSync("out/AvalancheTrustEscrow.sol/AvalancheTrustEscrow.json", "utf8"));
const out = "../frontend/src/contracts/AvalancheTrustEscrow.abi.ts";
fs.writeFileSync(out,
  "// Auto-generated by contracts/script/export-abi.sh. Do not edit by hand.\n" +
  "export const avalancheTrustEscrowAbi = " + JSON.stringify(artifact.abi, null, 2) + " as const;\n");
console.log("ABI written to " + out);
'
